name: Build

on: [push]

jobs:
  build_ubuntu_latests_no_cuda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install criterion
      run: |
        source ./scripts/actions/install_criterion.sh
        if [[ $? -eq 0 ]]; then
          echo "Criterion installed"
        fi
      shell: bash

    - name: Build without cuda
      run: ./build.sh -r simulator

    - name: Test without cuda
      run:  ./run_tests.sh

  build_ubuntu_latest_cuda11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build without cuda
      run: ./build.sh -r simulator

    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
        method: 'network'
        linux-local-args: '["--toolkit"]'

    - name: Build with cuda 11
      run: ./build.sh -r simulator

  build_ubuntu_latest_cuda12:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build without cuda
      run: ./build.sh -r simulator

    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        method: 'network'
        linux-local-args: '["--toolkit"]'

    - name: Build with cuda 12
      run: ./build.sh -r simulator
